replicaCount: 1

image:
  repository: python
  tag: "3.12-slim"
  pullPolicy: IfNotPresent

logMessage: "Hello from logginapp!"
logInterval: 5

service:
  port: 8080

servicemonitor:
  enabled: false

metrics:
  path: /metrics
  interval: 15s
